version: "3.5"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.12.2
    container_name: artifactory
    networks:
    - devops_pipeline
    ports:
     - 8081:8081
    volumes:
     - artifactory_container_data:/var/opt/jfrog/artifactory
    environment:
     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx1g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
    - "8080:8080"
    networks:
    - devops_pipeline
    restart: always
    volumes:
    - jenkins_container_data:/var/jenkins_home
  sonarqube:
    image: sonarqube
    container_name: code_scanner
    ports:
    - "9000:9000"
    restart: always
    networks:
    - devops_pipeline
    volumes:
    - sonarqube_container_data:/opt/sonarqube
   
networks:
  devops_pipeline:
    driver: overlay

volumes:
  jenkins_container_data:
    name: jenkins_container
    driver: local
  sonarqube_container_data:
    name: sonarqube_container
    driver: local
  artifactory_container_data:
    name: artifactory_container
    driver: local
